#!/usr/bin/env bash
# EUROART — GCP deployment bootstrap
#
# Interactive setup that:
#   1. asks for your service-account JSON key and deployment settings,
#   2. stores the key as a GitHub Actions secret (GCP_SA_KEY),
#   3. generates .github/workflows/deploy-gcp.yml which deploys the static
#      site to a Cloud Storage bucket on every push to the chosen branch.
#
# The SA key itself is NEVER written into the repository.
#
# Requirements:
#   - bash, python3 (for JSON parsing)
#   - gh CLI authenticated against the repo (optional — without it the
#     script prints the secret-setup instructions instead)
#
# The service account needs roles/storage.admin (or storage.objectAdmin on
# an existing bucket plus storage.buckets.get).

set -euo pipefail

bold=$(tput bold 2>/dev/null || true); dim=$(tput dim 2>/dev/null || true)
yel=$(tput setaf 3 2>/dev/null || true); blu=$(tput setaf 4 2>/dev/null || true)
rst=$(tput sgr0 2>/dev/null || true)

repo_root=$(cd "$(dirname "$0")/.." && pwd)
workflow_dir="$repo_root/.github/workflows"
workflow_file="$workflow_dir/deploy-gcp.yml"

echo
echo "${yel}${bold}  ▄▄ EUROART ▄▄${rst}  ${blu}${bold}GCP deployment bootstrap${rst}"
echo "  ${dim}Static site → Cloud Storage bucket via GitHub Actions${rst}"
echo

ask() { # ask <prompt> <default> -> REPLY
  local prompt="$1" default="${2:-}"
  if [ -n "$default" ]; then
    read -r -p "  ${prompt} ${dim}[${default}]${rst}: " REPLY
    REPLY="${REPLY:-$default}"
  else
    while true; do
      read -r -p "  ${prompt}: " REPLY
      [ -n "$REPLY" ] && break
      echo "  ${yel}This value is required.${rst}"
    done
  fi
}

# ── 1. Service-account key ─────────────────────────────────────────
while true; do
  ask "Path to service-account JSON key" ""
  sa_path="${REPLY/#\~/$HOME}"
  if [ ! -f "$sa_path" ]; then
    echo "  ${yel}File not found: $sa_path${rst}"
    continue
  fi
  if sa_info=$(python3 - "$sa_path" <<'PY'
import json, sys
d = json.load(open(sys.argv[1]))
assert d.get("type") == "service_account", "not a service-account key"
print(d["project_id"]); print(d["client_email"])
PY
  ); then
    sa_project=$(echo "$sa_info" | sed -n 1p)
    sa_email=$(echo "$sa_info" | sed -n 2p)
    echo "  ${dim}✓ key for ${sa_email}${rst}"
    break
  else
    echo "  ${yel}That file is not a valid service-account JSON key.${rst}"
  fi
done

# ── 2. Deployment settings ─────────────────────────────────────────
ask "GCP project ID" "$sa_project";                 project="$REPLY"
ask "Cloud Storage bucket name" "euroart-web";      bucket="$REPLY"
ask "Bucket location/region" "europe-west1";        region="$REPLY"
ask "Deploy on pushes to branch" "main";            branch="$REPLY"

echo
echo "  ${bold}Summary${rst}"
echo "    project : $project"
echo "    bucket  : gs://$bucket  ($region)"
echo "    branch  : $branch"
echo "    SA      : $sa_email"
echo "    secret  : GCP_SA_KEY (GitHub Actions)"
echo
read -r -p "  Proceed? [Y/n]: " ok
case "${ok:-Y}" in [Yy]*|"") ;; *) echo "  Aborted."; exit 1;; esac

# ── 3. GitHub secret ───────────────────────────────────────────────
echo
if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
  gh secret set GCP_SA_KEY < "$sa_path"
  echo "  ${dim}✓ secret GCP_SA_KEY set via gh CLI${rst}"
else
  echo "  ${yel}gh CLI not available — set the secret manually:${rst}"
  echo "    GitHub → repo → Settings → Secrets and variables → Actions"
  echo "    → New repository secret → name: GCP_SA_KEY"
  echo "    → value: the full contents of $sa_path"
fi

# ── 4. Workflow ────────────────────────────────────────────────────
mkdir -p "$workflow_dir"
cat > "$workflow_file" <<YML
# Generated by deploy/bootstrap-gcp.sh — deploys the static site to
# gs://$bucket on every push to '$branch'.
name: Deploy to GCP

on:
  push:
    branches: ["$branch"]
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: deploy-gcp
  cancel-in-progress: true

env:
  PROJECT_ID: $project
  BUCKET: $bucket
  REGION: $region

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: \${{ secrets.GCP_SA_KEY }}

      - name: Set up gcloud
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: \${{ env.PROJECT_ID }}

      - name: Create bucket if it does not exist
        run: |
          if ! gcloud storage buckets describe "gs://\$BUCKET" >/dev/null 2>&1; then
            gcloud storage buckets create "gs://\$BUCKET" \\
              --project="\$PROJECT_ID" --location="\$REGION" \\
              --uniform-bucket-level-access
            gcloud storage buckets add-iam-policy-binding "gs://\$BUCKET" \\
              --member=allUsers --role=roles/storage.objectViewer
            gcloud storage buckets update "gs://\$BUCKET" \\
              --web-main-page-suffix=index.html --web-error-page=index.html
          fi

      - name: Sync site to bucket
        run: |
          gcloud storage rsync . "gs://\$BUCKET" --recursive --delete-unmatched-destination-objects \\
            --exclude="^\\.git/.*|^\\.github/.*|^deploy/.*|^README\\.md\$"

      - name: Set cache headers
        run: |
          gcloud storage objects update "gs://\$BUCKET/index.html" \\
            --cache-control="public, max-age=300"
          for prefix in assets css js; do
            gcloud storage objects update "gs://\$BUCKET/\$prefix/**" \\
              --cache-control="public, max-age=86400" || true
          done

      - name: Done
        run: echo "Deployed → https://storage.googleapis.com/\$BUCKET/index.html"
YML

echo "  ${dim}✓ workflow written to .github/workflows/deploy-gcp.yml${rst}"
echo
echo "  ${bold}Next steps${rst}"
echo "    1. Review and commit the workflow:"
echo "         git add .github/workflows/deploy-gcp.yml && git commit -m 'Add GCP deploy workflow'"
echo "    2. Push to '$branch' (or run the workflow manually from the Actions tab)."
echo "    3. Site URL: https://storage.googleapis.com/$bucket/index.html"
echo "       ${dim}For a custom domain, point the bucket behind a load balancer or"
echo "       name the bucket after the domain and add a CNAME.${rst}"
echo
